### ISSUE TITLE
CT: event indexing failed:

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#301]
```
john-travoltage : phet-io-tests
6 out of 7 tests passed. 1 failed.
SimTests: john-travoltage: event indexing failed:
Expected at least one assertion, but none were run - call expect(0) to accept zero assertions.
    at testInputEventIndexing (https://bayes.colorado.edu/continuous-testing/snapshot-1537200530369/phet-io-wrappers/js/tests/SimTests.js?bust=1537202748936:394:11)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1537200530369/phet-io-wrappers/js/tests/SimTests.js?bust=1537202748936:464:5
    at Object.execCb (https://bayes.colorado.edu/continuous-testing/snapshot-1537200530369/sherpa/lib/require-2.1.11.js:1650:25)
    at Module.check (https://bayes.colorado.edu/continuous-testing/snapshot-1537200530369/sherpa/lib/require-2.1.11.js:866:35)
    at Module.enable (https://bayes.colorado.edu/continuous-testing/snapshot-1537200530369/sherpa/lib/require-2.1.11.js:1143:14)
    at Module.init (https://bayes.colorado.edu/continuous-testing/snapshot-1537200530369/sherpa/lib/require-2.1.11.js:774:16)
    at callGetModule (https://bayes.colorado.edu/continuous-testing/snapshot-1537200530369/sherpa/lib/require-2.1.11.js:1170:55)


Approximately 9/17/2018, 10:08:50 AM
```

**Comment by jbphet** [comment]
Should be fixed.  I had a bad assert statement that is now corrected.  I'll look at CT in a few hours and, if all looks good, I'll close.

**Comment by jbphet** [comment]
CT is no longer failing, closing.

**Comment by jbphet** [comment]
Coulomb's Law is failing CT, and the error message looks like it is related to this.  Here's the most recent error message as of this writing:

```
coulombs-law : phet-io-fuzz : require.js : load
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/assert/js/assert.js:22:13)
    at Tandem.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/tandem/js/Tandem.js?bust=1537224416897:101:21)
    at Property.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/tandem/js/PhetioObject.js?bust=1537224416897:151:19)
    at Property.PhetioObject [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/tandem/js/PhetioObject.js?bust=1537224416897:80:12)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/axon/js/Property.js?bust=1537224416897:84:18)
    at CLMacroScreen.Screen [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/joist/js/Screen.js?bust=1537224416897:130:27)
    at new CLMacroScreen (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/coulombs-law/js/macro/CLMacroScreen.js?bust=1537224416897:40:12)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/coulombs-law/js/coulombs-law-main.js?bust=1537224416897:47:5
    at Object.execCb (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/sherpa/lib/require-2.1.11.js:1650:25)
    at Module.check (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/sherpa/lib/require-2.1.11.js:866:35)
Approximately 9/17/2018, 4:28:48 PM
coulombs-law : phet-io-fuzz : require.js : run
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/assert/js/assert.js:22:13)
    at Tandem.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/tandem/js/Tandem.js?bust=1537224416897:101:21)
    at Property.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/tandem/js/PhetioObject.js?bust=1537224416897:151:19)
    at Property.PhetioObject [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/tandem/js/PhetioObject.js?bust=1537224416897:80:12)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/axon/js/Property.js?bust=1537224416897:84:18)
    at CLMacroScreen.Screen [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/joist/js/Screen.js?bust=1537224416897:130:27)
    at new CLMacroScreen (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/coulombs-law/js/macro/CLMacroScreen.js?bust=1537224416897:40:12)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/coulombs-law/js/coulombs-law-main.js?bust=1537224416897:47:5
    at Object.execCb (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/sherpa/lib/require-2.1.11.js:1650:25)
    at Module.check (https://bayes.colorado.edu/continuous-testing/snapshot-1537223328419/sherpa/lib/require-2.1.11.js:866:35)
Approximately 9/17/2018, 4:28:48 PM
coulombs-law : phet-io-tests
7 out of 7 tests passed. 0 failed.

Approximately 9/17/2018, 4:28:48 
```

Reopening for @zepumph to have a look.

**Comment by KatieWoe** [comment]
@jbphet this issue seems to have reappeared. 
```
john-travoltage : phet-io-tests
6 out of 7 tests passed. 1 failed.
SimTests: john-travoltage: event indexing failed:
Expected at least one assertion, but none were run - call expect(0) to accept zero assertions.
    at testInputEventIndexing (https://bayes.colorado.edu/continuous-testing/snapshot-1537541091904/phet-io-wrappers/js/tests/SimTests.js?bust=1537541926834:394:11)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1537541091904/phet-io-wrappers/js/tests/SimTests.js?bust=1537541926834:464:5
    at Object.execCb (https://bayes.colorado.edu/continuous-testing/snapshot-1537541091904/sherpa/lib/require-2.1.11.js:1650:25)
    at Module.check (https://bayes.colorado.edu/continuous-testing/snapshot-1537541091904/sherpa/lib/require-2.1.11.js:866:35)
    at Module.enable (https://bayes.colorado.edu/continuous-testing/snapshot-1537541091904/sherpa/lib/require-2.1.11.js:1143:14)
    at Module.init (https://bayes.colorado.edu/continuous-testing/snapshot-1537541091904/sherpa/lib/require-2.1.11.js:774:16)
    at callGetModule (https://bayes.colorado.edu/continuous-testing/snapshot-1537541091904/sherpa/lib/require-2.1.11.js:1170:55)


Approximately 9/21/2018, 8:44:51 AM
```

**Comment by jbphet** [comment]
The latest CT failure was actually due to a different problem, but not matter - it should now be fixed.  Closing.
