### ISSUE TITLE
CT: iframe api failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#327]
```
john-travoltage : phet-io-tests : assert
6 out of 7 tests passed. 1 failed.
SimTests: john-travoltage: iframe api failed:
Changed state on startup should be empty, but instead includes: johnTravoltage.johnTravoltageScreen.model.shoeOnCarpetProperty
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/js/tests/SimTests.js?bust=1549362891698:150:20)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:319:83)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:371:19)

SimTests: john-travoltage: iframe api failed:
Changed state should now have one item in it.
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/js/tests/SimTests.js?bust=1549362891698:164:24)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:319:83)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:371:19)

SimTests: john-travoltage: iframe api failed:
Changed state should now have one item in it.
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/js/tests/SimTests.js?bust=1549362891698:188:30)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:319:83)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:371:19)


id: Bayes Chrome
Approximately 2/5/2019, 12:29:16 AM
john-travoltage : phet-io-tests : assert
6 out of 7 tests passed. 1 failed.
SimTests: john-travoltage: iframe api failed:
Changed state on startup should be empty, but instead includes: johnTravoltage.johnTravoltageScreen.model.shoeOnCarpetProperty
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/js/tests/SimTests.js?bust=1549369035043:150:20)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:319:83)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:371:19)

SimTests: john-travoltage: iframe api failed:
Changed state should now have one item in it.
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/js/tests/SimTests.js?bust=1549369035043:164:24)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:319:83)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:371:19)

SimTests: john-travoltage: iframe api failed:
Changed state should now have one item in it.
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/js/tests/SimTests.js?bust=1549369035043:188:30)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:319:83)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:371:19)


id: Bayes Chrome
Approximately 2/5/2019, 12:29:16 AM
john-travoltage : phet-io-tests : assert
6 out of 7 tests passed. 1 failed.
SimTests: john-travoltage: iframe api failed:
Changed state on startup should be empty, but instead includes: johnTravoltage.johnTravoltageScreen.model.shoeOnCarpetProperty
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/js/tests/SimTests.js?bust=1549383473813:150:20)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:319:83)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:371:19)

SimTests: john-travoltage: iframe api failed:
Changed state should now have one item in it.
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/js/tests/SimTests.js?bust=1549383473813:164:24)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:319:83)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:371:19)


id: Bayes Chrome
Approximately 2/5/2019, 12:29:16 AM
john-travoltage : phet-io-tests : no-assert
6 out of 7 tests passed. 1 failed.
SimTests: john-travoltage: iframe api failed:
Changed state on startup should be empty, but instead includes: johnTravoltage.johnTravoltageScreen.model.shoeOnCarpetProperty
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/js/tests/SimTests.js?bust=1549358128713:150:20)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:319:83)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:371:19)

SimTests: john-travoltage: iframe api failed:
Changed state should now have one item in it.
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/js/tests/SimTests.js?bust=1549358128713:164:24)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:319:83)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:371:19)

SimTests: john-travoltage: iframe api failed:
Changed state should now have one item in it.
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/js/tests/SimTests.js?bust=1549358128713:188:30)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:319:83)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:371:19)


id: Bayes Chrome
Approximately 2/5/2019, 12:29:16 AM
john-travoltage : phet-io-tests : no-assert
6 out of 7 tests passed. 1 failed.
SimTests: john-travoltage: iframe api failed:
Changed state on startup should be empty, but instead includes: johnTravoltage.johnTravoltageScreen.model.shoeOnCarpetProperty
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/js/tests/SimTests.js?bust=1549377882914:150:20)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:319:83)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:371:19)

SimTests: john-travoltage: iframe api failed:
Changed state should now have one item in it.
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/js/tests/SimTests.js?bust=1549377882914:164:24)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:319:83)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:371:19)

SimTests: john-travoltage: iframe api failed:
Changed state should now have one item in it.
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/js/tests/SimTests.js?bust=1549377882914:188:30)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:319:83)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:371:19)


id: Bayes Chrome
Approximately 2/5/2019, 12:29:16 AM
john-travoltage : phet-io-tests : no-assert
6 out of 7 tests passed. 1 failed.
SimTests: john-travoltage: iframe api failed:
Changed state on startup should be empty, but instead includes: johnTravoltage.johnTravoltageScreen.model.shoeOnCarpetProperty
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/js/tests/SimTests.js?bust=1549379589228:150:20)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:319:83)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:371:19)

SimTests: john-travoltage: iframe api failed:
Changed state should now have one item in it.
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/js/tests/SimTests.js?bust=1549379589228:164:24)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:319:83)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io-wrappers/common/js/Client.js:371:19)


id: Bayes Chrome
Approximately 2/5/2019, 12:29:16 AM
```

**Comment by samreid** [comment]
@chrisklus and I committed a fix which seems to resolve this issue.
