### ISSUE TITLE
CT Object should be null or a truthy object that cannot have an extra prototype

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#344]
```
john-travoltage : accessibility-fuzz : require.js : load
Query: brand=phet&ea&fuzz&a11y&memoryLimit=1000
Uncaught Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/assert/js/assert.js?bust=1583758357086:22:13)
    at validateMergeableObject (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:59:13)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:31:7
    at arrayEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583758357086:537:11)
    at Function.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583758357086:9359:14)
    at merge (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:29:5)
    at new ShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tappi/js/view/ShapeHitDetector.js:40:15)
    at new BodyShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/BodyShapeHitDetector.js:17:5)
    at new JohnTravoltageView (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/JohnTravoltageView.js:137:27)
    at JohnTravoltageScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/JohnTravoltageScreen.js:26:14)
id: Bayes Chrome
Approximately 3/9/2020, 3:16:42 AM
john-travoltage : accessibility-fuzz : require.js : run
Query: brand=phet&ea&fuzz&a11y&memoryLimit=1000
Uncaught Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/assert/js/assert.js?bust=1583758357086:22:13)
    at validateMergeableObject (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:59:13)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:31:7
    at arrayEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583758357086:537:11)
    at Function.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583758357086:9359:14)
    at merge (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:29:5)
    at new ShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tappi/js/view/ShapeHitDetector.js:40:15)
    at new BodyShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/BodyShapeHitDetector.js:17:5)
    at new JohnTravoltageView (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/JohnTravoltageView.js:137:27)
    at JohnTravoltageScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/JohnTravoltageScreen.js:26:14)
id: Bayes Chrome
Approximately 3/9/2020, 3:16:42 AM
john-travoltage : accessibility-fuzzBoard : require.js : load
Query: brand=phet&ea&fuzzBoard&a11y&memoryLimit=1000
Uncaught Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/assert/js/assert.js?bust=1583748490374:22:13)
    at validateMergeableObject (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:59:13)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:31:7
    at arrayEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583748490374:537:11)
    at Function.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583748490374:9359:14)
    at merge (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:29:5)
    at new ShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tappi/js/view/ShapeHitDetector.js:40:15)
    at new BodyShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/BodyShapeHitDetector.js:17:5)
    at new JohnTravoltageView (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/JohnTravoltageView.js:137:27)
    at JohnTravoltageScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/JohnTravoltageScreen.js:26:14)
id: Bayes Chrome
Approximately 3/9/2020, 3:16:42 AM
john-travoltage : accessibility-fuzzBoard : require.js : run
Query: brand=phet&ea&fuzzBoard&a11y&memoryLimit=1000
Uncaught Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/assert/js/assert.js?bust=1583748490374:22:13)
    at validateMergeableObject (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:59:13)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:31:7
    at arrayEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583748490374:537:11)
    at Function.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583748490374:9359:14)
    at merge (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:29:5)
    at new ShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tappi/js/view/ShapeHitDetector.js:40:15)
    at new BodyShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/BodyShapeHitDetector.js:17:5)
    at new JohnTravoltageView (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/JohnTravoltageView.js:137:27)
    at JohnTravoltageScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/JohnTravoltageScreen.js:26:14)
id: Bayes Chrome
Approximately 3/9/2020, 3:16:42 AM
john-travoltage : fuzz : require.js : load
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/assert/js/assert.js?bust=1583747819409:22:13)
    at validateMergeableObject (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:59:13)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:31:7
    at arrayEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583747819409:537:11)
    at Function.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583747819409:9359:14)
    at merge (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:29:5)
    at new ShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tappi/js/view/ShapeHitDetector.js:40:15)
    at new BodyShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/BodyShapeHitDetector.js:17:5)
    at new JohnTravoltageView (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/JohnTravoltageView.js:137:27)
    at JohnTravoltageScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/JohnTravoltageScreen.js:26:14)
id: Bayes Chrome
Approximately 3/9/2020, 3:16:42 AM
john-travoltage : fuzz : require.js : load
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/assert/js/assert.js?bust=1583765519688:22:13)
    at validateMergeableObject (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:59:13)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:31:7
    at arrayEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583765519688:537:11)
    at Function.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583765519688:9359:14)
    at merge (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:29:5)
    at new ShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tappi/js/view/ShapeHitDetector.js:40:15)
    at new BodyShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/BodyShapeHitDetector.js:17:5)
    at new JohnTravoltageView (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/JohnTravoltageView.js:137:27)
    at JohnTravoltageScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/JohnTravoltageScreen.js:26:14)
id: Bayes Chrome
Approximately 3/9/2020, 3:16:42 AM
john-travoltage : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/assert/js/assert.js?bust=1583747819409:22:13)
    at validateMergeableObject (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:59:13)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:31:7
    at arrayEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583747819409:537:11)
    at Function.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583747819409:9359:14)
    at merge (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:29:5)
    at new ShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tappi/js/view/ShapeHitDetector.js:40:15)
    at new BodyShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/BodyShapeHitDetector.js:17:5)
    at new JohnTravoltageView (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/JohnTravoltageView.js:137:27)
    at JohnTravoltageScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/JohnTravoltageScreen.js:26:14)
id: Bayes Chrome
Approximately 3/9/2020, 3:16:42 AM
john-travoltage : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/assert/js/assert.js?bust=1583765519688:22:13)
    at validateMergeableObject (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:59:13)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:31:7
    at arrayEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583765519688:537:11)
    at Function.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583765519688:9359:14)
    at merge (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:29:5)
    at new ShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tappi/js/view/ShapeHitDetector.js:40:15)
    at new BodyShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/BodyShapeHitDetector.js:17:5)
    at new JohnTravoltageView (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/JohnTravoltageView.js:137:27)
    at JohnTravoltageScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/JohnTravoltageScreen.js:26:14)
id: Bayes Chrome
Approximately 3/9/2020, 3:16:42 AM
john-travoltage : phet-io-fuzz : require.js : load
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/assert/js/assert.js?bust=1583754086227:22:13)
    at validateMergeableObject (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:59:13)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:31:7
    at arrayEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583754086227:537:11)
    at Function.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583754086227:9359:14)
    at merge (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:29:5)
    at new ShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tappi/js/view/ShapeHitDetector.js:40:15)
    at new BodyShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/BodyShapeHitDetector.js:17:5)
    at new JohnTravoltageView (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/JohnTravoltageView.js:137:27)
    at JohnTravoltageScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/JohnTravoltageScreen.js:26:14)
id: Bayes Chrome
Approximately 3/9/2020, 3:16:42 AM
john-travoltage : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/assert/js/assert.js?bust=1583754086227:22:13)
    at validateMergeableObject (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:59:13)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:31:7
    at arrayEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583754086227:537:11)
    at Function.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583754086227:9359:14)
    at merge (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:29:5)
    at new ShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tappi/js/view/ShapeHitDetector.js:40:15)
    at new BodyShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/BodyShapeHitDetector.js:17:5)
    at new JohnTravoltageView (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/JohnTravoltageView.js:137:27)
    at JohnTravoltageScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/JohnTravoltageScreen.js:26:14)
id: Bayes Chrome
Approximately 3/9/2020, 3:16:42 AM
john-travoltage : phet-io-state-fuzz : require.js : load
Uncaught Error: Uncaught Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/assert/js/assert.js?bust=1583749701781:22:13)
    at validateMergeableObject (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:59:13)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:31:7
    at arrayEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583749701781:537:11)
    at Function.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583749701781:9359:14)
    at merge (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:29:5)
    at new ShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tappi/js/view/ShapeHitDetector.js:40:15)
    at new BodyShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/BodyShapeHitDetector.js:17:5)
    at new JohnTravoltageView (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/JohnTravoltageView.js:137:27)
    at JohnTravoltageScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/JohnTravoltageScreen.js:26:14)
id: Bayes Chrome
Approximately 3/9/2020, 3:16:42 AM
john-travoltage : phet-io-state-fuzz : require.js : run
Uncaught Error: Uncaught Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/assert/js/assert.js?bust=1583749701781:22:13)
    at validateMergeableObject (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:59:13)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:31:7
    at arrayEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583749701781:537:11)
    at Function.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583749701781:9359:14)
    at merge (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:29:5)
    at new ShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tappi/js/view/ShapeHitDetector.js:40:15)
    at new BodyShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/BodyShapeHitDetector.js:17:5)
    at new JohnTravoltageView (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/JohnTravoltageView.js:137:27)
    at JohnTravoltageScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/JohnTravoltageScreen.js:26:14)
id: Bayes Chrome
Approximately 3/9/2020, 3:16:42 AM
john-travoltage : phet-io-studio-fuzz : require.js : load
Uncaught Error: Uncaught Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/assert/js/assert.js?bust=1583748126630:22:13)
    at validateMergeableObject (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:59:13)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:31:7
    at arrayEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583748126630:537:11)
    at Function.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583748126630:9359:14)
    at merge (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:29:5)
    at new ShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tappi/js/view/ShapeHitDetector.js:40:15)
    at new BodyShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/BodyShapeHitDetector.js:17:5)
    at new JohnTravoltageView (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/JohnTravoltageView.js:137:27)
    at JohnTravoltageScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/JohnTravoltageScreen.js:26:14)
id: Bayes Chrome
Approximately 3/9/2020, 3:16:42 AM
john-travoltage : phet-io-studio-fuzz : require.js : run
Uncaught Error: Uncaught Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/assert/js/assert.js?bust=1583748126630:22:13)
    at validateMergeableObject (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:59:13)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:31:7
    at arrayEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583748126630:537:11)
    at Function.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583748126630:9359:14)
    at merge (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:29:5)
    at new ShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tappi/js/view/ShapeHitDetector.js:40:15)
    at new BodyShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/BodyShapeHitDetector.js:17:5)
    at new JohnTravoltageView (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/JohnTravoltageView.js:137:27)
    at JohnTravoltageScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/JohnTravoltageScreen.js:26:14)
id: Bayes Chrome
Approximately 3/9/2020, 3:16:42 AM
john-travoltage : xss-fuzz : load
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/assert/js/assert.js?bust=1583748130854:22:13)
    at validateMergeableObject (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:59:13)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:31:7
    at arrayEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583748130854:537:11)
    at Function.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583748130854:9359:14)
    at merge (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:29:5)
    at new ShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tappi/js/view/ShapeHitDetector.js:40:15)
    at new BodyShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/BodyShapeHitDetector.js:17:5)
    at new JohnTravoltageView (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/JohnTravoltageView.js:137:27)
    at JohnTravoltageScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/JohnTravoltageScreen.js:26:14)
id: Bayes Chrome
Approximately 3/9/2020, 3:16:42 AM
john-travoltage : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
Error: Assertion failed: Object should be null or a truthy  object that cannot have an extra prototype
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/assert/js/assert.js?bust=1583748130854:22:13)
    at validateMergeableObject (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:59:13)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:31:7
    at arrayEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583748130854:537:11)
    at Function.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/sherpa/lib/lodash-4.17.4.js?bust=1583748130854:9359:14)
    at merge (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-core/js/merge.js:29:5)
    at new ShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tappi/js/view/ShapeHitDetector.js:40:15)
    at new BodyShapeHitDetector (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/BodyShapeHitDetector.js:17:5)
    at new JohnTravoltageView (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/view/JohnTravoltageView.js:137:27)
    at JohnTravoltageScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/john-travoltage/js/john-travoltage/JohnTravoltageScreen.js:26:14)
id: Bayes Chrome
Approximately 3/9/2020, 3:16:42 AM
```

**Comment by KatieWoe** [comment]
Seen when testing ES6 phet-io.
![jtbug](https://user-images.githubusercontent.com/41024075/76261662-19d3ae00-6220-11ea-99cf-3c2409e49d9b.png)

**Comment by samreid** [comment]
We will likely work on this during the upcoming phet-io instrumentation.  Unassigning until then.

**Comment by jessegreenberg** [comment]
This has not appeared in CT for a long time, closing.
