### ISSUE TITLE
CT relative pitch value out of range

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#347]
```
john-travoltage : phet-io-state-fuzz : require.js
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588854684647/phet-io-wrappers/state/?sim=john-travoltage&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22john-travoltage%22%2C%22phet-io-state-fuzz%22%2C%22require.js%22%5D%2C%22snapshotName%22%3A%22snapshot-1588854684647%22%2C%22timestamp%22%3A1588858053779%7D
Uncaught Error: Assertion failed: relative pitch value out of range
Error: Assertion failed: relative pitch value out of range
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588854684647/assert/js/assert.js:22:13)
at PitchedPopGenerator.playPop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588854684647/tambo/js/sound-generators/PitchedPopGenerator.js:92:15)
at lengthChangedListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588854684647/john-travoltage/js/john-travoltage/view/JohnTravoltageView.js:366:23)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588854684647/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588854684647/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588854684647/axon/js/Action.js:224:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588854684647/axon/js/Emitter.js:58:19)
at PhetioGroup.disposeElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588854684647/tandem/js/PhetioDynamicElementContainer.js:125:33)
at PhetioGroup.disposeElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588854684647/tandem/js/PhetioGroup.js:83:11)
at PhetioGroup.clear (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588854684647/tandem/js/PhetioGroup.js:168:12)
id: Bayes Chrome
Snapshot from 5/7/2020, 6:31:24 AM
```

**Comment by samreid** [comment]
@jbphet or @zepumph can you please take a look?

**Comment by pixelzoom** [comment]
@zepumph suspects that this is due to https://github.com/phetsims/phet-io/issues/1661.

**Comment by zepumph** [comment]
It wasn't because of https://github.com/phetsims/phet-io/issues/1661! I don't know exactly what caused it, or fixed it, but CT is clear now. Likely it is from work done over in https://github.com/phetsims/tandem/issues/170

**Comment by zepumph** [comment]
I'm going to close this issue.
