### ISSUE TITLE
CT countProperty should match array length

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#348]
```
john-travoltage : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589809891236/phet-io-wrappers/state/?sim=john-travoltage&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22john-travoltage%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589809891236%22%2C%22timestamp%22%3A1589812410096%7D
Uncaught Error: Assertion failed: countProperty should match array length.
Error: Assertion failed: countProperty should match array length.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589809891236/assert/js/assert.js:22:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589809891236/tandem/js/PhetioGroup.js:69:9
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589809891236/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589809891236/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589809891236/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589809891236/axon/js/Emitter.js:58:19)
at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589809891236/phet-io/js/PhetioStateEngine.js:215:26)
at PhetioEngineIO.implementation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589809891236/phet-io/js/PhetioEngineIO.js:221:43)
at PhetioCommandProcessor.processCommand (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589809891236/phet-io/js/phetioCommandProcessor.js:267:51)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589809891236/phet-io/js/phetioCommandProcessor.js:160:36
id: Bayes Chrome
Snapshot from 5/18/2020, 7:51:31 AM
```

**Comment by zepumph** [comment]
This is because of https://github.com/phetsims/phet-io/issues/1668, and similar in cause to https://github.com/phetsims/projectile-motion/issues/229. I'll look at this later this week.

**Comment by zepumph** [comment]
This was much easier to find than https://github.com/phetsims/projectile-motion/issues/229, likely since I know what I was looking for, and it was easier to reproduce. Here is the patch that game me the paused on the stack trace when extra electrons were being added during state set. This would likely have been just as useful in PM if I had thought about it. 

<details>

```diff
Index: assert/js/assert.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- assert/js/assert.js	(revision 0b7a48c6b9ba48af48ae7419bd30c280c785f2cc)
+++ assert/js/assert.js	(date 1590093821833)
@@ -18,7 +18,7 @@
       }
 
       const logMessage = message ? 'Assertion failed: ' + message : 'Assertion failed';
-      console && console.log && console.log(  logMessage );
+      console && console.log && console.log(  logMessage );debugger;
       throw new Error( logMessage );
     }
   };
Index: tandem/js/PhetioGroup.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tandem/js/PhetioGroup.js	(revision 5a480cb89ab8c17d9fd7f75ba15b151b714f5fa0)
+++ tandem/js/PhetioGroup.js	(date 1590093893274)
@@ -229,8 +229,11 @@
    * @returns {PhetioObject}
    * @public (PhetioGroupIO)
    */
-  createIndexedElement( index, argsForCreateFunction ) {
+  createIndexedElement( index, argsForCreateFunction, temp ) {
 
+    if ( !temp && phet.joist.sim.isSettingPhetioStateProperty.value ) {
+      debugger;
+    }
     const componentName = this.phetioDynamicElementName + window.phetio.PhetioIDUtils.GROUP_SEPARATOR + index;
     const containerParameterType = this.phetioType.parameterTypes[ 0 ];
     const groupElement = this.createDynamicElement( componentName, argsForCreateFunction, containerParameterType );
Index: tandem/js/PhetioGroupIO.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tandem/js/PhetioGroupIO.js	(revision 5a480cb89ab8c17d9fd7f75ba15b151b714f5fa0)
+++ tandem/js/PhetioGroupIO.js	(date 1590093893270)
@@ -69,7 +69,7 @@
 
       const index = window.phetio.PhetioIDUtils.getGroupElementIndex( componentName );
 
-      const groupElement = group.createIndexedElement( index, args );
+      const groupElement = group.createIndexedElement( index, args, true );
 
       // Keep the groupElementIndex in sync so that the next index is set appropriately. This covers the case where
       // no elements have been created in the sim, instead they have only been set via state.

```
</details>

**Comment by zepumph** [comment]
I'll reopen if this doesn't clear on CT.
