### ISSUE TITLE
CT Unloaded frame before complete

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#450]
```
john-travoltage : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/john-travoltage/john-travoltage_en.html?continuousTest=%7B%22test%22%3A%5B%22john-travoltage%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1631352162505%22%2C%22timestamp%22%3A1631693119175%7D&brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Unloaded frame before complete, window.location probably changed
id: Bayes Chrome
Snapshot from 9/11/2021, 3:22:42 AM

----------------------------------

john-travoltage : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/john-travoltage/john-travoltage_en.html?continuousTest=%7B%22test%22%3A%5B%22john-travoltage%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1631352162505%22%2C%22timestamp%22%3A1631428609267%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: must be connected to a display to use UtteranceQueue features
Error: Assertion failed: must be connected to a display to use UtteranceQueue features
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/assert/js/assert.js:25:13)
at VisualPreferencesPanel.alertDescriptionUtterance (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/scenery/js/accessibility/pdom/ParallelDOM.js:2683:19)
at alertEnabledChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/joist/js/preferences/VisualPreferencesPanel.js:67:12)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/axon/js/TinyEmitter.js:86:9)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/axon/js/Property.js:271:23)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/axon/js/Property.js:186:14)
at BooleanProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/axon/js/Property.js:341:32)
at ToggleSwitch.Action.parameters.validValues (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/sun/js/ToggleSwitch.js:169:22)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/axon/js/Action.js:227:18)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631352162505/sun/js/ToggleSwitch.js:239:24)
id: Bayes Chrome
Snapshot from 9/11/2021, 3:22:42 AM
```

**Comment by jessegreenberg** [comment]
This one is an artifact of CT that happens sometimes. I am not sure why exactly but it is not an issue with simulation code.
