### ISSUE TITLE
CT this.angleToPDOMValueFunction is not a function

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#453]
```
john-travoltage : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/john-travoltage/john-travoltage_en.html?continuousTest=%7B%22test%22%3A%5B%22john-travoltage%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1637683103029%22%2C%22timestamp%22%3A1637685416624%7D&brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught TypeError: this.angleToPDOMValueFunction is not a function
TypeError: this.angleToPDOMValueFunction is not a function
at LegNode.a11yAngleToPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/john-travoltage/js/john-travoltage/view/AppendageNode.js:243:42)
at map (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/john-travoltage/js/john-travoltage/view/AppendageNode.js:182:32)
at new DynamicProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/axon/js/DynamicProperty.js:137:13)
at new AppendageNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/john-travoltage/js/john-travoltage/view/AppendageNode.js:180:31)
at new LegNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/john-travoltage/js/john-travoltage/view/LegNode.js:57:9)
at new JohnTravoltageView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/john-travoltage/js/john-travoltage/view/JohnTravoltageView.js:109:24)
at JohnTravoltageScreen.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/john-travoltage/js/john-travoltage/JohnTravoltageScreen.js:18:85)
at JohnTravoltageScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/joist/js/Screen.js:206:27)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/joist/js/Sim.js:609:24)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/joist/js/Sim.js:616:29
id: Bayes Chrome
Snapshot from 11/23/2021, 8:58:23 AM

----------------------------------

john-travoltage : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/john-travoltage/john-travoltage_en.html?continuousTest=%7B%22test%22%3A%5B%22john-travoltage%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1637683103029%22%2C%22timestamp%22%3A1637685560036%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught TypeError: this.angleToPDOMValueFunction is not a function
TypeError: this.angleToPDOMValueFunction is not a function
at LegNode.a11yAngleToPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/john-travoltage/js/john-travoltage/view/AppendageNode.js:243:42)
at map (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/john-travoltage/js/john-travoltage/view/AppendageNode.js:182:32)
at new DynamicProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/axon/js/DynamicProperty.js:137:13)
at new AppendageNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/john-travoltage/js/john-travoltage/view/AppendageNode.js:180:31)
at new LegNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/john-travoltage/js/john-travoltage/view/LegNode.js:57:9)
at new JohnTravoltageView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/john-travoltage/js/john-travoltage/view/JohnTravoltageView.js:109:24)
at JohnTravoltageScreen.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/john-travoltage/js/john-travoltage/JohnTravoltageScreen.js:18:85)
at JohnTravoltageScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/joist/js/Screen.js:206:27)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/joist/js/Sim.js:609:24)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637683103029/chipper/dist/joist/js/Sim.js:616:29
id: Bayes Chrome
Snapshot from 11/23/2021, 8:58:23 AM
```

**Comment by jessegreenberg** [comment]
This has not been in john-travoltage for a long time and was likely a common code issue. Closing.
