### ISSUE TITLE
CT: Assertion failed: reentry detected (VoicingToolbarItem)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/john-travoltage#460]
Looks like this started appearing in CT on 3/16/2022, 1:18:58 AM, and has been appearing on every cycle since.  Entry point for the failure is `VoicingToolbarItem`. I don't see it in other sims.

```
john-travoltage : voicing-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647415138856/john-travoltage/john-travoltage_en.html?continuousTest=%7B%22test%22%3A%5B%22john-travoltage%22%2C%22voicing-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647415138856%22%2C%22timestamp%22%3A1647416982933%7D&brand=phet&ea&fuzz&voicingInitiallyEnabled&memoryLimit=1000
Query: brand=phet&ea&fuzz&voicingInitiallyEnabled&memoryLimit=1000
Uncaught Error: Assertion failed: reentry detected, value=false, oldValue=true
Error: Assertion failed: reentry detected, value=false, oldValue=true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647415138856/assert/js/assert.js:25:13)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647415138856/chipper/dist/js/axon/js/Property.js:225:15)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647415138856/chipper/dist/js/axon/js/Property.js:156:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647415138856/chipper/dist/js/joist/js/toolbar/VoicingToolbarItem.js:169:30
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647415138856/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647415138856/chipper/dist/js/axon/js/Emitter.js:47:22)
at VoicingManager.handleSpeechSynthesisEnd (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647415138856/chipper/dist/js/utterance-queue/js/SpeechSynthesisAnnouncer.js:433:29)
at SpeechSynthesisUtterance.endListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647415138856/chipper/dist/js/utterance-queue/js/SpeechSynthesisAnnouncer.js:395:12)
at VoicingManager.requestSpeech (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647415138856/chipper/dist/js/utterance-queue/js/SpeechSynthesisAnnouncer.js:420:21)
at VoicingManager.announce (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647415138856/chipper/dist/js/utterance-queue/js/SpeechSynthesisAnnouncer.js:328:12)
id: Bayes Chrome
Snapshot from 3/16/2022, 1:18:58 AM
```

**Comment by jessegreenberg** [comment]
Github won't let me transfer so Ill do that later.

Ive been fuzzing for 15 minutes locally and haven't seen the issue yet.

**Comment by jessegreenberg** [comment]
I am guessing this just started showing up because voicing tests were recently added to CT? My theory is this is the first time testing SpeechSynthesis on headles chrome. The stack starts with

```
voicingManager.announce()
voicingManager.requestSpeech()
SpeechSynthesisUtterance.endListener
```

So to me that means that the end listener fires immediately and synchronously with the speech request which would set the Property back to false in a reentrant way. Maybe this would happen if headless chrome shuts down all SpeechSynthesis requests.

**Comment by zepumph** [comment]
@jessegreenberg, does it seem buggy to you though? I'm alright with headless chrome causing an sync call synchronously as long as you think that the queue/Announcer is still managing things correctly. The reentrant call may be helpful to keep voicing code being tested on CT.
