### ISSUE TITLE
CT no description found for pitch at value: 1.4999999999999996

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#461]
```
john-travoltage : voicing-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647568115292/john-travoltage/john-travoltage_en.html?continuousTest=%7B%22test%22%3A%5B%22john-travoltage%22%2C%22voicing-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647568115292%22%2C%22timestamp%22%3A1647576528865%7D&brand=phet&ea&fuzzBoard&voicingInitiallyEnabled&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&voicingInitiallyEnabled&memoryLimit=1000
Uncaught Error: Assertion failed: no description found for pitch at value: 1.4999999999999996
Error: Assertion failed: no description found for pitch at value: 1.4999999999999996
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647568115292/assert/js/assert.js:25:13)
at VoicingPitchSlider.getPitchDescriptionString (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647568115292/chipper/dist/js/joist/js/preferences/VoicingPanelSection.js:468:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647568115292/chipper/dist/js/joist/js/preferences/VoicingPanelSection.js:435:41
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647568115292/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647568115292/chipper/dist/js/axon/js/Property.js:227:23)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647568115292/chipper/dist/js/axon/js/Property.js:156:14)
at HSlider.handleKeyDown (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647568115292/chipper/dist/js/sun/js/accessibility/AccessibleValueHandler.js:418:33)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647568115292/chipper/dist/js/scenery/js/input/Input.js:1740:23)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647568115292/chipper/dist/js/scenery/js/input/Input.js:1775:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647568115292/chipper/dist/js/scenery/js/input/Input.js:1698:10)
id: Bayes Chrome
Snapshot from 3/17/2022, 7:48:35 PM
```

**Comment by jessegreenberg** [comment]
Fixed with the above commit.
