### ISSUE TITLE
CT cannot set state while setting state

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#462]
```
john-travoltage : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653490621067/phet-io-wrappers/state/?sim=john-travoltage&phetioDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22john-travoltage%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1653490621067%22%2C%22timestamp%22%3A1653492507675%7D
Uncaught Error: Uncaught Error: Assertion failed: cannot set state while setting state
Error: Assertion failed: cannot set state while setting state
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653490621067/assert/js/assert.js:28:13)
at assert (PhetioStateEngine.js:224:14)
at setState (PhetioStateEngine.js:263:9)
at setFullState (phetioEngine.js:1105:31)
at apply (phetioCommandProcessor.js:304:50)
at processCommand (phetioCommandProcessor.js:179:35)
at getReturn (phetioCommandProcessor.js:183:15)
at Array.map
at map (phetioCommandProcessor.js:177:29)
at processCommands (phetioCommandProcessor.js:113:15)
id: Bayes Chrome
Snapshot from 5/25/2022, 8:57:01 AM
```

**Comment by zepumph** [comment]
See https://github.com/phetsims/phet-io-wrappers/issues/441

**Comment by jessegreenberg** [comment]
It seems this is potentially a common code problem, closing this issue.
